#!/bin/bash

echo "What would you like to do:"
echo "1) Append Time"
echo "2) List appended time"
echo "3) Add time"
echo "4) Remove existing time "
echo "5) Quit"

read -p "Enter your choice: " choice

case $choice in
  1)
    sh ./time1
    ;;
  2)
    cat ./time.txt
    ;;
  3)
    awk '{ sum += $1 } END { print sum }' ./time.txt
    ;;
  4) 
    rm ./time.txt && touch time.txt 
    ;;
  5)
    echo "Quitting."
    exit 0
    ;;
  *)
    echo "Invalid choice. Try again."
    ;;
esac


